name: CD
on:
  push:
    tags:
      - "[v]?[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish:
    name: Publishing for ${{ matrix.job.os }}
    runs-on: ${{ matrix.job.os }}
    permissions:
      contents: write
    strategy:
      fail-fast: false

      matrix:
        build_type: [Release]
        architecture: [x86_64]
        project-name: [lz-string]
        cmake-args:
          [-DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -G "Ninja"]
        job:
          - os: macos-latest
            os-name: macos
            lib-prefix: "lib"
            lib-postfix: ".a"
          - os: ubuntu-latest
            os-name: linux
            lib-prefix: "lib"
            lib-postfix: ".a"
          - os: windows-latest
            os-name: windows
            lib-prefix: ""
            lib-postfix: ".lib"

    steps:
      - uses: actions/checkout@v4

      - name: Set Reusable Strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=$GITHUB_WORKSPACE/build" >> "$GITHUB_OUTPUT"

      - name: Configure CMake
        env:
          CXX: clang++
        working-directory: ${{github.workspace}}
        run: cmake ${{matrix.cmake-args}} -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -B ${{steps.strings.outputs.build-output-dir}}

      - name: Build
        run: cmake --build ${{steps.strings.outputs.build-output-dir}} --config ${{matrix.build_type}} -j8

      - name: Packaging Final Binary
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE/build

          LIB_NAME=${{matrix.job.lib-prefix}}${{matrix.project-name}}${{matrix.job.lib-postfix}}

          RELEASE_NAME=${{matrix.project-name}}-${GITHUB_REF/refs\/tags\//}-${{matrix.job.os-name}}-${{matrix.architecture}}
          tar czvf $RELEASE_NAME.tar.gz $LIB_NAME ../includes

          if [[ ${{ runner.os }} == 'Windows' ]]; then
            certutil -hashfile $RELEASE_NAME.tar.gz sha256 | grep -E [A-Fa-f0-9]{64} > $RELEASE_NAME.sha256
          else
            shasum -a 256 $RELEASE_NAME.tar.gz > $RELEASE_NAME.sha256
          fi

      - name: Releasing Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{steps.strings.outputs.build-output-dir}}/${{matrix.project-name}}-*.tar.gz
            ${{steps.strings.outputs.build-output-dir}}/${{matrix.project-name}}-*.sha256
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
